# Γραμμική Άλγεβρα με Python

In [1]:
import numpy as np

\begin{equation}
A = 
\begin{bmatrix}
1 & 2 & 3 & 4 \\
10 & 20 & 30 & 40 \\
4 & 3 & 2 & 1 \\
0.2 & 0.3 & 0.4 & 0.1
\end{bmatrix}
\end{equation}

## 1. Κατασκευή Πίνακα

### Κατασκευή πίνακα από απευθείας γραμμένες λίστες γραμμών

In [2]:
r1 = [1,2,3,4]
r2 = [10,20,30,40]
r3 = [4,3,2,1]
r4 = [0.2,0.3,0.4,0.1]
m = [r1,r2,r3,r4]
A = np.array(m)
print A

[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]


### Κατασκευή πίνακα από λίστες γραμμών γραμμένων με εντολές

In [3]:
r1 = range(1,5)
r2 = range(10,50,10)
r3 = range(1,5)[::-1]
r4 = [i/10. for i in r1[1:]]+[0.1]
A1 = np.array([r1,r2,r3,r4])
print A1
print np.array_equal(A1, A)
A1 == A

[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]
True


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

### Κατασκευή πίνακα από λίστες στηλών

In [4]:
c1 = A[:,0]   #c1 = [1, 10, 4, 0.2]
c2 = A[:,1]   #c2 = [2, 20, 3, 0.3]
c3 = A[:,2]   #c3 = [3, 30, 2, 0.4]
c4 = A[:,3]   #c4 = [4, 40, 1, 0.1]
m1 = zip(c1,c2,c3,c4)
A2 = np.array(m1)
print A2
np.array_equal(A2, A)

[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]


True

### Κατασκευή πίνακα από πίνακα μηδενικών (ή μονάδων)

In [5]:
A3 = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        A3[i,j] = m[i][j]
print A3
print np.array_equal(A3, A)

Ones = np.ones((4,4))
print Ones

[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]
True
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [6]:
Ones = np.ones((3,4))
print Ones

I5 = np.eye(5)
print I5
I5_1u = np.eye(5,k=1)
print I5_1u
I5_2l = np.eye(5,k=-2)
print I5_2l

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
[[ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]]


### Κατασκευή πίνακα από λίστα με reshape

In [7]:
# An exoume lista n stoixeiwn kai theloume na ta anadiataxoume se m grammes kai k steiles, opou n = m*k
# DEN DOYLEYEI apevtheis me to range(n) alla me to np.arange(n)

np.arange(24).reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [8]:
rr = range(24)
np.array(rr).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### Κατασκευή πίνακα από λίστες τυχαίων αριθμών

In [9]:
import random

#### Δημιουργία λίστας ακέραιων με random.randrange

In [10]:
a = [random.randrange(1,4) for i in range(4)]
a

[2, 1, 1, 1]

#### Δημιουργία λίστας με random.choice

In [11]:
a = [random.randrange(9) for i in range(4)]
a

[0, 8, 7, 4]

#### Δημιουργία λίστας με random.sample (χωρίς επαναλήψεις)

In [12]:
a = random.sample(range(9),4) 
a

[2, 8, 5, 0]

#### Δημιουργία λίστας πραγματικών αριθμών στο διάστημα [a, b] με random.uniform

In [13]:
a = [random.uniform(10,40) for i in range(4)]
a

[12.807940781553647, 12.707747817281039, 34.06321723446226, 15.249813108011999]

#### Δημιουργία λίστας/πίνακα πραγματικών αριθμών με np.random.randn μέσω της τυπικής κανονικής κατανομής

In [14]:
a = np.random.randn(1,4) 
a

array([[-0.22636092,  1.17144259, -1.75988932,  0.24490661]])

In [15]:
C = np.random.randn(4,4) 
C

array([[-1.62062338,  0.06809332, -0.48431273,  0.85627636],
       [ 1.07174682,  0.21731038,  0.20215667, -0.32062055],
       [-0.56059213, -2.23331795,  0.74594566,  0.01800064],
       [ 1.80129077, -0.32525232, -1.75043792, -0.7236049 ]])

## 2. Πρόσθεση, Αφαίρεση και Πολλαπλασιασμός Πινάκων με Αριθμό

In [16]:
print 'A =' 
print A
print 'C =' 
print C
print
print 'A + 100 ='
print A + 100
print 'A + C ='
print A + C
print '-10*A ='
print -10*C

A =
[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]
C =
[[-1.62062338  0.06809332 -0.48431273  0.85627636]
 [ 1.07174682  0.21731038  0.20215667 -0.32062055]
 [-0.56059213 -2.23331795  0.74594566  0.01800064]
 [ 1.80129077 -0.32525232 -1.75043792 -0.7236049 ]]

A + 100 =
[[ 101.   102.   103.   104. ]
 [ 110.   120.   130.   140. ]
 [ 104.   103.   102.   101. ]
 [ 100.2  100.3  100.4  100.1]]
A + C =
[[ -6.20623380e-01   2.06809332e+00   2.51568727e+00   4.85627636e+00]
 [  1.10717468e+01   2.02173104e+01   3.02021567e+01   3.96793794e+01]
 [  3.43940787e+00   7.66682053e-01   2.74594566e+00   1.01800064e+00]
 [  2.00129077e+00  -2.52523229e-02  -1.35043792e+00  -6.23604899e-01]]
-10*A =
[[ 16.2062338   -0.68093321   4.84312728  -8.56276355]
 [-10.71746819  -2.17310382  -2.02156674   3.20620555]
 [  5.60592125  22.33317947  -7.45945659  -0.1800064 ]
 [-18.01290767   3.25252323  17.50437916   7.23604899]]


## 3. Διάσταση Πινάκων (Διανυσμάτων)

In [17]:
A.shape

(4, 4)

In [18]:
A[0,:].shape

(4,)

In [19]:
A[:,0].shape

(4,)

In [20]:
D = np.random.randn(3,4) 
D.shape

(3, 4)

## 4. Πολλαπλασιασμός Δυο Πινάκων

In [21]:
print D.shape
print A.shape
D.dot(A)

(3, 4)
(4, 4)


array([[ 18.7176613 ,  26.20201861,  33.68637592,  40.86947821],
       [ 27.42966757,  49.19565499,  70.96164242,  92.99885065],
       [ 18.04620874,  33.45532826,  48.86444777,  64.38772006]])

In [22]:
np.dot(D,A)

array([[ 18.7176613 ,  26.20201861,  33.68637592,  40.86947821],
       [ 27.42966757,  49.19565499,  70.96164242,  92.99885065],
       [ 18.04620874,  33.45532826,  48.86444777,  64.38772006]])

In [23]:
A.dot(D)

ValueError: shapes (4,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

## 5. Αναστροφή Πίνακα

In [24]:
A = np.random.randn(2,4) 
print 'A ='
print A
print A.shape
print 'Atranspose ='
print A.T
print A.T.shape

A =
[[-0.33749742  2.04439066  1.23964427  0.34780544]
 [ 2.10915673  1.55379106  0.55375927  0.92477312]]
(2, 4)
Atranspose =
[[-0.33749742  2.10915673]
 [ 2.04439066  1.55379106]
 [ 1.23964427  0.55375927]
 [ 0.34780544  0.92477312]]
(4, 2)


## 6. Εσωτερικό Γινόμενο Δυο Διανυσμάτων

In [25]:
u = np.random.randn(1,4) 
v = np.random.randn(4,1) 
print 'u dot v ='
print u.dot(v)

u dot v =
[[ 1.92281816]]


In [26]:
x = np.random.randn(1,5) 
y = np.arange(5)
print 'x dot y ='
print x.dot(y.T)

x dot y =
[ 5.57962939]


## 7. Ορίζουσα Πίνακα

In [27]:
A = np.random.randn(5,5)
print 'detA ='
print np.linalg.det(A)

detA =
-3.14730475155


In [28]:
A = np.arange(25).reshape(5,5)
print 'detA ='
print np.linalg.det(A)

detA =
0.0


In [29]:
A = np.arange(24).reshape(4,6)
np.linalg.det(A)

LinAlgError: Last 2 dimensions of the array must be square

## 8. Ίχνος Πίνακα

In [30]:
A = np.random.randn(5,5)
print 'traceA ='
print np.trace(A)

traceA =
-1.09403694175


## 9. Αντιστροφή Πίνακα

In [31]:
A = np.array([random.sample(range(9),4) for i in range(4)])
print A
print 'A-1 ='
print np.linalg.inv(A)

[[3 2 4 6]
 [3 4 2 5]
 [6 4 2 8]
 [7 3 5 0]]
A-1 =
[[-0.10769231 -0.25641026  0.24102564  0.09230769]
 [-0.18461538  0.51282051 -0.18205128  0.01538462]
 [ 0.26153846  0.05128205 -0.22820513  0.06153846]
 [ 0.10769231 -0.07692308  0.09230769 -0.09230769]]


## 10. Επίλυση Γραμμικού Συστήματος

\begin{equation}
\begin{bmatrix}
1 & -2 & -3 & 4 \\
-10 & -20 & 30 & 40 \\
4 & -3 & 2 & -1 \\
0.2 & 0.3 & -0.4 & 0.1
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z \\
w
\end{bmatrix}
=
\begin{bmatrix}
100 \\
200 \\
300 \\
400
\end{bmatrix}
\end{equation}

In [32]:
r1 = [1,-2,-3,4]
r2 = [-10,-20,30,40]
r3 = [4,-3,2,-1]
r4 = [0.2,0.3,-0.4,0.1]
m = [r1,r2,r3,r4]
A = np.array(m)

x = np.array(['x','y','z','w'])
b = np.array([100,200,300,400])

sol = np.linalg.inv(A).dot(b)
print 'x =', sol[0]
print 'y =', sol[1]
print 'z =', sol[2]
print 'w =', sol[3]

x = 801.25
y = 970.714285714
z = 253.75
w = 500.357142857


## 11. Ιδιοτιμές και Ιδιοδιανύσματα Πίνακα

In [33]:
A = np.random.randn(6,6)
print 'A ='
print A
eigenvalues, eigenvectors = np.linalg.eig(A)
print 'Eigenvalues of A ='
print eigenvalues
print 'Eigenvectors of A ='
print eigenvectors
print
A = np.array([random.randrange(2) for i in range(16)]).reshape(4,4)
print 'A ='
print A
print 'Eigenvalues of A ='
print eigenvalues
print np.linalg.eig(A)[0]
print 'Eigenvectors of A ='
print np.linalg.eig(A)[1]

A =
[[ 0.70102894 -0.53414482 -0.51884261 -1.70466229  0.379865   -1.05886919]
 [-0.05384654  1.15551949  0.31802627 -0.14451389  0.61520713  0.77278067]
 [-0.48749334  1.50549617 -1.10049178  0.11298644  0.95244408 -0.90172593]
 [-0.52124049  0.17911571 -0.24386242 -0.44459732 -0.79891981 -0.14855599]
 [-0.97592608  0.29624152  2.52800431  0.308031    0.28718781  0.03373886]
 [ 1.21477149  0.2224247   0.05862254 -0.37350476 -0.84691569  0.02090694]]
Eigenvalues of A =
[ 2.05105938+0.j          1.26293389+1.23698592j  1.26293389-1.23698592j
 -1.27137739+0.83525013j -1.27137739-0.83525013j -1.41461831+0.j        ]
Eigenvectors of A =
[[-0.12629509+0.j         -0.57319929+0.j         -0.57319929-0.j
  -0.11238864+0.36858214j -0.11238864-0.36858214j -0.41276455+0.j        ]
 [-0.56412748+0.j         -0.05063179+0.13739583j -0.05063179-0.13739583j
  -0.19560134-0.09167135j -0.19560134+0.09167135j  0.10172148+0.j        ]
 [-0.45396422+0.j         -0.03613594-0.27269474j -0.03613594+0.27269