# Γραμμική Άλγεβρα με Python

In [1]:
import numpy as np

\begin{equation}
A = 
\begin{bmatrix}
1 & 2 & 3 & 4 \\
10 & 20 & 30 & 40 \\
4 & 3 & 2 & 1 \\
0.2 & 0.3 & 0.4 & 0.1
\end{bmatrix}
\end{equation}

## 1. Κατασκευή Πίνακα

### Κατασκευή πίνακα από απευθείας γραμμένες λίστες γραμμών

In [2]:
r1 = [1,2,3,4]
r2 = [10,20,30,40]
r3 = [4,3,2,1]
r4 = [0.2,0.3,0.4,0.1]
m = [r1,r2,r3,r4]
A = np.array(m)
print A

[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]


### Κατασκευή πίνακα από λίστες γραμμών γραμμένων με εντολές

In [3]:
r1 = range(1,5)
r2 = range(10,50,10)
r3 = range(1,5)[::-1]
r4 = [i/10. for i in r1[1:]]+[0.1]
A1 = np.array([r1,r2,r3,r4])
print A1
print np.array_equal(A1, A)
A1 == A

[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]
True


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

### Κατασκευή πίνακα από λίστες στηλών

In [4]:
c1 = A[:,0]   #c1 = [1, 10, 4, 0.2]
c2 = A[:,1]   #c2 = [2, 20, 3, 0.3]
c3 = A[:,2]   #c3 = [3, 30, 2, 0.4]
c4 = A[:,3]   #c4 = [4, 40, 1, 0.1]
m1 = zip(c1,c2,c3,c4)
A2 = np.array(m1)
print A2
np.array_equal(A,A2)

[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]


True

In [5]:
r1=[2,3,3]
r2=[1,2,2]
A=np.array([r1,r2])
print A
c1=[2,1]
c2=[3,2]
c3=[3,2]
B=np.array(zip(c1,c2,c3))
print B
print np.array_equal(A,B)

[[2 3 3]
 [1 2 2]]
[[2 3 3]
 [1 2 2]]
True


In [6]:
# H prosbasi sto stoixeio 1,2 me tin arithmisi apo 1
print A[0,1]
# Prosbasi sti lista twn stoixeiwn tis tritis stilis
print A[:,2]
# Prosbasi sti lista twn stoixeiwn tis devteris grammis
print A[1,:]
print A[:,:]

3
[3 2]
[1 2 2]
[[2 3 3]
 [1 2 2]]


In [7]:
# Megrthos pinaka A.shape pou epistrefei tin dyada: 
# (arithos grammwn,arithmos stilwn)
print 'shape.A =', A.shape
print 'plithos grammwn =', A.shape[0]
print 'plithos stilwwn =', A.shape[1]

shape.A = (2, 3)
plithos grammwn = 2
plithos stilwwn = 3


In [8]:
B = np.array([[1,7,8,3],[3,5,8,6],[1,2,3,4],[3,9,7,6]])
print B
# H lista twn diagwniwn stoixeiwn tou pinaka me for loop
diagwnioi_oroi = []
for i in range(B.shape[0]):
    diagwnioi_oroi.append(B[i,i])
print diagwnioi_oroi

[[1 7 8 3]
 [3 5 8 6]
 [1 2 3 4]
 [3 9 7 6]]
[1, 5, 3, 6]


### Κατασκευή πίνακα από πίνακα μηδενικών (ή μονάδων)

In [9]:
A3 = np.zeros((4,4))
print A3

for i in range(4):
    for j in range(4):
        A3[i,j] = m[i][j]
print A3
print np.array_equal(A3, A)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]
False


In [10]:
Ones = np.ones((3,4))
print Ones

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [11]:
I5 = np.eye(5)
print I5
I5_1u = np.eye(5,k=1)
print I5_1u
I5_2l = np.eye(5,k=-2)
print I5_2l

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
[[ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]]


### Κατασκευή πίνακα από λίστα με reshape

In [12]:
# An exoume lista n stoixeiwn kai theloume na ta anadiataxoume se m grammes kai k steiles, opou n = m*k
# DEN DOYLEYEI apevtheis me to range(n) alla me to np.arange(n)

np.arange(24).reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [13]:
rr = range(24)
np.array(rr).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### Άσκηση ΓΑ1

Ξεκινώντας από τη λίστα των περιττών αριθμών από 0 ως 40, κατασκευάστε έναν πίνακα M1 5x4 με reshape. Τυπώστε την τέταρτη γραμμή και την δεύτερη στήλη του M1.

### Άσκηση ΓΑ2

Ξεκινώντας από πίνακα μηδενικών, κατασκευάστε τον πίνακα Μ1 της Άσκησης ΓΑ1.

### Κατασκευή πίνακα από λίστες τυχαίων αριθμών

In [62]:
import random

#### Δημιουργία λίστας ακέραιων με random.randrange

In [10]:
a = [random.randrange(1,4) for i in range(4)]
a

[2, 1, 1, 1]

#### Δημιουργία λίστας με random.choice

In [11]:
a = [random.randrange(9) for i in range(4)]
a

[0, 8, 7, 4]

#### Δημιουργία λίστας με random.sample (χωρίς επαναλήψεις)

In [12]:
a = random.sample(range(9),4) 
a

[2, 8, 5, 0]

#### Δημιουργία λίστας πραγματικών αριθμών στο διάστημα [a, b] με random.uniform

In [13]:
a = [random.uniform(10,40) for i in range(4)]
a

[12.807940781553647, 12.707747817281039, 34.06321723446226, 15.249813108011999]

#### Δημιουργία λίστας/πίνακα πραγματικών αριθμών με np.random.randn μέσω της τυπικής κανονικής κατανομής

In [14]:
a = np.random.randn(1,4) 
a

array([[-0.22636092,  1.17144259, -1.75988932,  0.24490661]])

In [15]:
C = np.random.randn(4,4) 
C

array([[-1.62062338,  0.06809332, -0.48431273,  0.85627636],
       [ 1.07174682,  0.21731038,  0.20215667, -0.32062055],
       [-0.56059213, -2.23331795,  0.74594566,  0.01800064],
       [ 1.80129077, -0.32525232, -1.75043792, -0.7236049 ]])

### Άσκηση ΓΑ3

Κατασκευάστε έναν πίνακα M3 4x5 με ακέραια στοιχεία μέσω της μεθόδου random.randrange. Τυπώστε την δεύτερη γραμμή και την τρίτη στήλη του M3.

### Άσκηση ΓΑ4

Κατασκευάστε έναν πίνακα M4 3x2 με ακέραια στοιχεία μέσω της μεθόδου random.choice. Τυπώστε την πρώτη γραμμή και την δεύτερη στήλη του M4.

### Άσκηση ΓΑ5

Κατασκευάστε έναν πίνακα M5 6x6 με ακέραια στοιχεία μέσω της μεθόδου random.sample. Τυπώστε την διαγώνιο του M5.

### Άσκηση ΓΑ6

Κατασκευάστε έναν πίνακα M6 4x4 με στοιχεία πραγματικούς αριθμούς στο διάστημα [-10,10) μέσω της μεθόδου random.uniform. Τυπώστε την αντιδιαγώνιο του M6.

### Άσκηση ΓΑ7

Κατασκευάστε έναν πίνακα M7 3x4 με στοιχεία πραγματικούς αριθμούς μέσω της μεθόδου random.randn. Βρείτε/τυπώστε τη λίστα των στοιχείων του Μ7 που είναι < 0.7 και > 0.3.

## 2. Πρόσθεση, Αφαίρεση και Πολλαπλασιασμός Πινάκων με Αριθμό

In [16]:
print 'A =' 
print A
print 'C =' 
print C
print
print 'A + 100 ='
print A + 100
print 'A + C ='
print A + C
print '-10*A ='
print -10*C

A =
[[  1.    2.    3.    4. ]
 [ 10.   20.   30.   40. ]
 [  4.    3.    2.    1. ]
 [  0.2   0.3   0.4   0.1]]
C =
[[-1.62062338  0.06809332 -0.48431273  0.85627636]
 [ 1.07174682  0.21731038  0.20215667 -0.32062055]
 [-0.56059213 -2.23331795  0.74594566  0.01800064]
 [ 1.80129077 -0.32525232 -1.75043792 -0.7236049 ]]

A + 100 =
[[ 101.   102.   103.   104. ]
 [ 110.   120.   130.   140. ]
 [ 104.   103.   102.   101. ]
 [ 100.2  100.3  100.4  100.1]]
A + C =
[[ -6.20623380e-01   2.06809332e+00   2.51568727e+00   4.85627636e+00]
 [  1.10717468e+01   2.02173104e+01   3.02021567e+01   3.96793794e+01]
 [  3.43940787e+00   7.66682053e-01   2.74594566e+00   1.01800064e+00]
 [  2.00129077e+00  -2.52523229e-02  -1.35043792e+00  -6.23604899e-01]]
-10*A =
[[ 16.2062338   -0.68093321   4.84312728  -8.56276355]
 [-10.71746819  -2.17310382  -2.02156674   3.20620555]
 [  5.60592125  22.33317947  -7.45945659  -0.1800064 ]
 [-18.01290767   3.25252323  17.50437916   7.23604899]]


## 3. Διάσταση Πινάκων (Διανυσμάτων)

In [17]:
A.shape

(4, 4)

In [18]:
A[0,:].shape

(4,)

In [19]:
A[:,0].shape

(4,)

In [24]:
D = np.random.randn(3,4) 
D.shape

(3, 4)

## 4. Πολλαπλασιασμός Δυο Πινάκων

In [21]:
print D.shape
print A.shape
D.dot(A)

(3, 4)
(4, 4)


array([[ 18.7176613 ,  26.20201861,  33.68637592,  40.86947821],
       [ 27.42966757,  49.19565499,  70.96164242,  92.99885065],
       [ 18.04620874,  33.45532826,  48.86444777,  64.38772006]])

In [22]:
np.dot(D,A)

array([[ 18.7176613 ,  26.20201861,  33.68637592,  40.86947821],
       [ 27.42966757,  49.19565499,  70.96164242,  92.99885065],
       [ 18.04620874,  33.45532826,  48.86444777,  64.38772006]])

In [23]:
A.dot(D)

ValueError: shapes (4,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

## 5. Αναστροφή Πίνακα

In [24]:
A = np.random.randn(2,4) 
print 'A ='
print A
print A.shape
print 'Atranspose ='
print A.T
print A.T.shape

A =
[[-0.33749742  2.04439066  1.23964427  0.34780544]
 [ 2.10915673  1.55379106  0.55375927  0.92477312]]
(2, 4)
Atranspose =
[[-0.33749742  2.10915673]
 [ 2.04439066  1.55379106]
 [ 1.23964427  0.55375927]
 [ 0.34780544  0.92477312]]
(4, 2)


## 6. Εσωτερικό Γινόμενο Δυο Διανυσμάτων

In [107]:
print 'u ='
print np.random.randn(4) 
print 'v ='
print np.random.randn(4) 
print 'u dot v ='
print u.dot(v)

u =
[ 0.72566518  0.40820883  0.78948233  0.77116135]
v =
[ 0.522227    1.49128771  0.61044608 -0.03423978]
u dot v =
1.36143941316


In [106]:
print 'x ='
print np.random.randn(5) 
print 'y ='
print np.arange(5)
print 'x dot y ='
print x.dot(y.T)

x =
[ 0.72913907  0.76051856 -0.34111573 -1.75005163  1.83821264]
y =
[0 1 2 3 4]
x dot y =
0.177226725349


## 7. Εξωτερικό Γινόμενο Δυο Διανυσμάτων

In [108]:
print 'u outer product v ='
print np.outer(u,v)
print 'v outer product u ='
print np.outer(v,u)
print np.array_equal(np.outer(u,v),np.outer(v,u).T)

u outer product v =
[[ 0.8344029  -0.62108398  0.45246043  0.19006384]
 [-0.43575818  0.32435461 -0.23629273 -0.09925885]
 [-0.06882835  0.05123207 -0.03732262 -0.01567801]
 [ 1.05364843 -0.78427838  0.57134775  0.24000452]]
v outer product u =
[[ 0.8344029  -0.43575818 -0.06882835  1.05364843]
 [-0.62108398  0.32435461  0.05123207 -0.78427838]
 [ 0.45246043 -0.23629273 -0.03732262  0.57134775]
 [ 0.19006384 -0.09925885 -0.01567801  0.24000452]]
True


In [109]:
print 'x outer product y ='
print np.outer(x,y)
print 'y outer product x ='
print np.outer(y,x)
print np.array_equal(np.outer(x,y),np.outer(y,x).T)

x outer product y =
[[-0.         -0.82815751 -1.65631502 -2.48447252 -3.31263003]
 [-0.         -0.54307073 -1.08614146 -1.62921219 -2.17228292]
 [-0.         -1.89878236 -3.79756471 -5.69634707 -7.59512943]
 [ 0.          0.99719995  1.9943999   2.99159984  3.98879979]
 [ 0.          0.38156558  0.76313116  1.14469674  1.52626233]]
y outer product x =
[[-0.         -0.         -0.          0.          0.        ]
 [-0.82815751 -0.54307073 -1.89878236  0.99719995  0.38156558]
 [-1.65631502 -1.08614146 -3.79756471  1.9943999   0.76313116]
 [-2.48447252 -1.62921219 -5.69634707  2.99159984  1.14469674]
 [-3.31263003 -2.17228292 -7.59512943  3.98879979  1.52626233]]
True


## 8. Νόρμες και Aποστάσεις Διανυσμάτων

In [111]:
from scipy.linalg import norm

print 'Euclidean norm of u ='
print np.linalg.norm(u)
print 'L1 norm of u ='
print norm(u,1) 
print 'L2 norm of u ='
print norm(u,2)
print 'L3 norm of u ='
print norm(u,3)
print 'Linfinity norm of u ='
print norm(u,np.inf)

Euclidean norm of u =
2.06455219027
L1 norm of u =
3.49201819814
L2 norm of u =
2.06455219027
L3 norm of u =
1.78639998935
Linfinity norm of u =
1.53778369124


In [114]:
print 'Euclidean distance of u, v ='
print np.linalg.norm(v-u)
print 'L1 distance of u, v ='
print np.linalg.norm(v-u,1)
print 'L2 distance of u, v ='
print np.linalg.norm(v-u,2)
print 'L3 distance of u, v ='
print np.linalg.norm(v-u,3)
print 'Linfinity distance of u, v ='
print np.linalg.norm(v-u,np.inf)
print np.linalg.norm(u-v) == np.linalg.norm(v-u)

Euclidean distance of u, v =
1.55931567993
L1 distance of u, v =
2.51230720993
L2 distance of u, v =
1.55931567993
L3 distance of u, v =
1.42540590754
Linfinity distance of u, v =
1.3817119857
True


## 9. Ορίζουσα Πίνακα

In [27]:
A = np.random.randn(5,5)
print 'detA ='
print np.linalg.det(A)

detA =
-3.14730475155


In [28]:
A = np.arange(25).reshape(5,5)
print 'detA ='
print np.linalg.det(A)

detA =
0.0


In [29]:
A = np.arange(24).reshape(4,6)
np.linalg.det(A)

LinAlgError: Last 2 dimensions of the array must be square

## 10. Ίχνος Πίνακα

In [30]:
A = np.random.randn(5,5)
print 'traceA ='
print np.trace(A)

traceA =
-1.09403694175


## 11. Αντιστροφή Πίνακα

In [31]:
A = np.array([random.sample(range(9),4) for i in range(4)])
print A
print 'A-1 ='
print np.linalg.inv(A)

[[3 2 4 6]
 [3 4 2 5]
 [6 4 2 8]
 [7 3 5 0]]
A-1 =
[[-0.10769231 -0.25641026  0.24102564  0.09230769]
 [-0.18461538  0.51282051 -0.18205128  0.01538462]
 [ 0.26153846  0.05128205 -0.22820513  0.06153846]
 [ 0.10769231 -0.07692308  0.09230769 -0.09230769]]


## 12. Επίλυση Γραμμικού Συστήματος

\begin{equation}
\begin{bmatrix}
1 & -2 & -3 & 4 \\
-10 & -20 & 30 & 40 \\
4 & -3 & 2 & -1 \\
0.2 & 0.3 & -0.4 & 0.1
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z \\
w
\end{bmatrix}
=
\begin{bmatrix}
100 \\
200 \\
300 \\
400
\end{bmatrix}
\end{equation}

#### Επίλυση μέσω αντίστροφου πίνακα

In [43]:
r1 = [1,-2,-3,4]
r2 = [-10,-20,30,40]
r3 = [4,-3,2,-1]
r4 = [0.2,0.3,-0.4,0.1]
m = [r1,r2,r3,r4]
A = np.array(m)

x = np.array(['x','y','z','w'])
b = np.array([100,200,300,400])

sol = np.linalg.inv(A).dot(b)
print 'x =', sol[0]
print 'y =', sol[1]
print 'z =', sol[2]
print 'w =', sol[3]

x = 801.25
y = 970.714285714
z = 253.75
w = 500.357142857


#### Απευθείας επίλυση

In [44]:
x = np.linalg.solve(A, b)
print 'x =', x[0]
print 'y =', x[1]
print 'z =', x[2]
print 'w =', x[3]

x = 801.25
y = 970.714285714
z = 253.75
w = 500.357142857


## 13. Τάξη (rank) και Μηδενικότητα (nullity) Πίνακα

* Η **τάξη** (**rank**) ενός πίνακα είναι η διάσταση του υπόχωρου των στηλών του (ή των γραμμών του).
* Ο **πυρήνας** (**kernel**) ενός πίνακα είναι τα διανύσματα που απεικονίζονται από τον πίνακα στο διάνυσμα 0.
* Η **μηδενικότητα** (**nullity**) ενός πίνακα είναι η διάσταση του πυρήνα του.
* Ισχύει ότι τάξη + μηδενικότητα = πλήθος στηλών του πίνακα.

In [22]:
from sympy import Matrix

B =  Matrix([[1, 2], [2, 4]])
print 'B ='
print B
print 'rank of B ='
print B.rank()
print 'kernel of B ='
print B.nullspace()
nullity = np.array(B.nullspace()).shape[0]
print 'nullity of B ='
print nullity
print B.rank() + nullity == B.shape[1]

B =
Matrix([[1, 2], [2, 4]])
rank of B =
1
kernel of B =
[Matrix([
[-2],
[ 1]])]
nullity of B =
1
True


## 14. Ιδιοτιμές και Ιδιοδιανύσματα Πίνακα

In [33]:
A = np.random.randn(6,6)
print 'A ='
print A
eigenvalues, eigenvectors = np.linalg.eig(A)
print 'Eigenvalues of A ='
print eigenvalues
print 'Eigenvectors of A ='
print eigenvectors
print
A = np.array([random.randrange(2) for i in range(16)]).reshape(4,4)
print 'A ='
print A
print 'Eigenvalues of A ='
print eigenvalues
print np.linalg.eig(A)[0]
print 'Eigenvectors of A ='
print np.linalg.eig(A)[1]

A =
[[ 0.70102894 -0.53414482 -0.51884261 -1.70466229  0.379865   -1.05886919]
 [-0.05384654  1.15551949  0.31802627 -0.14451389  0.61520713  0.77278067]
 [-0.48749334  1.50549617 -1.10049178  0.11298644  0.95244408 -0.90172593]
 [-0.52124049  0.17911571 -0.24386242 -0.44459732 -0.79891981 -0.14855599]
 [-0.97592608  0.29624152  2.52800431  0.308031    0.28718781  0.03373886]
 [ 1.21477149  0.2224247   0.05862254 -0.37350476 -0.84691569  0.02090694]]
Eigenvalues of A =
[ 2.05105938+0.j          1.26293389+1.23698592j  1.26293389-1.23698592j
 -1.27137739+0.83525013j -1.27137739-0.83525013j -1.41461831+0.j        ]
Eigenvectors of A =
[[-0.12629509+0.j         -0.57319929+0.j         -0.57319929-0.j
  -0.11238864+0.36858214j -0.11238864-0.36858214j -0.41276455+0.j        ]
 [-0.56412748+0.j         -0.05063179+0.13739583j -0.05063179-0.13739583j
  -0.19560134-0.09167135j -0.19560134+0.09167135j  0.10172148+0.j        ]
 [-0.45396422+0.j         -0.03613594-0.27269474j -0.03613594+0.27269